"""initial schema

Autogenerated and reviewed by hand: every table from docs/plan-backend.md, CHECK
constraints named ck_<table>_<name> (enum values and business rules), the FULLTEXT index
for product search and the virtual column behind "one default address per user".

Revision ID: 6041b0ca861d
Revises: 
Create Date: 2026-10-07 20:51:58.702742
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '6041b0ca861d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('attributes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attributes')),
    sa.UniqueConstraint('code', name=op.f('uq_attributes_code'))
    )
    op.create_table('brands',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Enum('percent', 'fixed', name='coupontype', native_enum=False, length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_subtotal_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('starts_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('ends_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`type` IN ('percent', 'fixed')", name=op.f('ck_coupons_type')),
    sa.CheckConstraint("type <> 'percent' OR value <= 100", name=op.f('ck_coupons_percent_max_100')),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name=op.f('ck_coupons_valid_period')),
    sa.CheckConstraint('max_uses IS NULL OR max_uses > 0', name=op.f('ck_coupons_max_uses_positive')),
    sa.CheckConstraint('max_uses_per_user IS NULL OR max_uses_per_user > 0', name=op.f('ck_coupons_max_uses_per_user_positive')),
    sa.CheckConstraint('used_count >= 0', name=op.f('ck_coupons_used_count_non_negative')),
    sa.CheckConstraint('value > 0', name=op.f('ck_coupons_value_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name=op.f('uq_coupons_code'))
    )
    op.create_table('pickup_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickup_points'))
    )
    op.create_table('shipping_zones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('free_over_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('eta_min_days', sa.Integer(), nullable=False),
    sa.Column('eta_max_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('cost_usd >= 0', name=op.f('ck_shipping_zones_cost_usd_non_negative')),
    sa.CheckConstraint('eta_min_days >= 0 AND eta_min_days <= eta_max_days', name=op.f('ck_shipping_zones_eta_range')),
    sa.CheckConstraint('free_over_usd IS NULL OR free_over_usd > 0', name=op.f('ck_shipping_zones_free_over_usd_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_zones')),
    sa.UniqueConstraint('code', name=op.f('uq_shipping_zones_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('customer', 'admin', name='userrole', native_enum=False, length=32), server_default='customer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_verified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_login_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`role` IN ('customer', 'admin')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('attribute_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attribute_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_attribute_values_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_values')),
    sa.UniqueConstraint('attribute_id', 'slug', name=op.f('uq_attribute_values_attribute_id_slug'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_id_created_at', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_entity_id', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.create_table('billing_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tax_id_type', sa.Enum('DNI', 'CUIT', name='taxidtype', native_enum=False, length=8), nullable=False),
    sa.Column('tax_id', sa.String(length=11), nullable=False),
    sa.Column('tax_condition', sa.Enum('consumidor_final', 'monotributo', 'responsable_inscripto', 'exento', name='taxcondition', native_enum=False, length=32), nullable=False),
    sa.Column('legal_name', sa.String(length=160), nullable=False),
    sa.Column('fiscal_address', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('default_user_id', sa.BigInteger(), sa.Computed('if(is_default, user_id, null)', persisted=False), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`tax_condition` IN ('consumidor_final', 'monotributo', 'responsable_inscripto', 'exento')", name=op.f('ck_billing_profiles_tax_condition')),
    sa.CheckConstraint("`tax_id_type` IN ('DNI', 'CUIT')", name=op.f('ck_billing_profiles_tax_id_type')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_billing_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_profiles')),
    sa.UniqueConstraint('default_user_id', name=op.f('uq_billing_profiles_default_user_id'))
    )
    op.create_index(op.f('ix_billing_profiles_user_id'), 'billing_profiles', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts')),
    sa.UniqueConstraint('user_id', name=op.f('uq_carts_user_id'))
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('rate > 0', name=op.f('ck_exchange_rates_rate_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exchange_rates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rates'))
    )
    op.create_index(op.f('ix_exchange_rates_created_by'), 'exchange_rates', ['created_by'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'paid', 'preparing', 'shipped', 'ready_for_pickup', 'delivered', 'cancelled', 'refunded', name='orderstatus', native_enum=False, length=32), server_default='pending_payment', nullable=False),
    sa.Column('currency', sa.Enum('ARS', 'USD', name='currency', native_enum=False), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('coupon_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_method', sa.Enum('pickup', 'shipping', name='deliverymethod', native_enum=False, length=16), nullable=False),
    sa.Column('shipping_snapshot', sa.JSON(), nullable=True),
    sa.Column('billing_snapshot', sa.JSON(), nullable=True),
    sa.Column('pickup_point_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('paid_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('cancelled_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`currency` IN ('ARS', 'USD')", name=op.f('ck_orders_currency')),
    sa.CheckConstraint("`delivery_method` IN ('pickup', 'shipping')", name=op.f('ck_orders_delivery_method')),
    sa.CheckConstraint("`status` IN ('pending_payment', 'paid', 'preparing', 'shipped', 'ready_for_pickup', 'delivered', 'cancelled', 'refunded')", name=op.f('ck_orders_status')),
    sa.CheckConstraint('exchange_rate > 0', name=op.f('ck_orders_exchange_rate_positive')),
    sa.CheckConstraint('subtotal >= 0 AND discount_total >= 0 AND shipping_total >= 0 AND total >= 0', name=op.f('ck_orders_amounts_non_negative')),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_orders_coupon_id_coupons')),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickup_points.id'], name=op.f('fk_orders_pickup_point_id_pickup_points')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('number', name=op.f('uq_orders_number')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name=op.f('uq_orders_user_id_idempotency_key'))
    )
    op.create_index(op.f('ix_orders_coupon_id'), 'orders', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_orders_pickup_point_id'), 'orders', ['pickup_point_id'], unique=False)
    op.create_index('ix_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('ix_orders_user_id_created_at', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('rating_avg BETWEEN 0 AND 5', name=op.f('ck_products_rating_avg_range')),
    sa.CheckConstraint('rating_count >= 0', name=op.f('ck_products_rating_count_non_negative')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_category_id_is_active', 'products', ['category_id', 'is_active'], unique=False)
    op.create_index('ix_products_is_featured_is_active', 'products', ['is_featured', 'is_active'], unique=False)
    op.create_table('provinces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('shipping_zone_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['shipping_zone_id'], ['shipping_zones.id'], name=op.f('fk_provinces_shipping_zone_id_shipping_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinces')),
    sa.UniqueConstraint('code', name=op.f('uq_provinces_code'))
    )
    op.create_index(op.f('ix_provinces_shipping_zone_id'), 'provinces', ['shipping_zone_id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('street', sa.String(length=120), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('floor_apt', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('default_user_id', sa.BigInteger(), sa.Computed('if(is_default, user_id, null)', persisted=False), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_addresses_province_id_provinces')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses')),
    sa.UniqueConstraint('default_user_id', name=op.f('uq_addresses_default_user_id'))
    )
    op.create_index(op.f('ix_addresses_province_id'), 'addresses', ['province_id'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_redemptions_coupon_id_coupons')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_redemptions_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupon_redemptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_redemptions')),
    sa.UniqueConstraint('order_id', name=op.f('uq_coupon_redemptions_order_id'))
    )
    op.create_index('ix_coupon_redemptions_coupon_id_user_id', 'coupon_redemptions', ['coupon_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_user_id'), 'coupon_redemptions', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_favorites_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name=op.f('pk_favorites'))
    )
    op.create_index(op.f('ix_favorites_product_id'), 'favorites', ['product_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.Enum('pending_payment', 'paid', 'preparing', 'shipped', 'ready_for_pickup', 'delivered', 'cancelled', 'refunded', name='orderstatus', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('pending_payment', 'paid', 'preparing', 'shipped', 'ready_for_pickup', 'delivered', 'cancelled', 'refunded', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`from_status` IN ('pending_payment', 'paid', 'preparing', 'shipped', 'ready_for_pickup', 'delivered', 'cancelled', 'refunded')", name=op.f('ck_order_status_history_from_status')),
    sa.CheckConstraint("`to_status` IN ('pending_payment', 'paid', 'preparing', 'shipped', 'ready_for_pickup', 'delivered', 'cancelled', 'refunded')", name=op.f('ck_order_status_history_to_status')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_order_status_history_changed_by_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history'))
    )
    op.create_index(op.f('ix_order_status_history_changed_by'), 'order_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'refunded', name='paymentstatus', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('ARS', 'USD', name='currency', native_enum=False), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`currency` IN ('ARS', 'USD')", name=op.f('ck_payments_currency')),
    sa.CheckConstraint("`status` IN ('pending', 'approved', 'rejected', 'refunded')", name=op.f('ck_payments_status')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider', 'provider_ref', name=op.f('uq_payments_provider_provider_ref'))
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('product_translations',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.Enum('es', 'en', name='locale', native_enum=False, length=5), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`locale` IN ('es', 'en')", name=op.f('ck_product_translations_locale')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_translations_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'locale', name=op.f('pk_product_translations'))
    )
    op.create_index('ix_product_translations_fulltext', 'product_translations', ['name', 'short_description'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('product_variants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_at_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('compare_at_price_usd IS NULL OR compare_at_price_usd > price_usd', name=op.f('ck_product_variants_compare_at_above_price')),
    sa.CheckConstraint('price_usd >= 0', name=op.f('ck_product_variants_price_usd_non_negative')),
    sa.CheckConstraint('stock >= 0', name=op.f('ck_product_variants_stock_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variants_sku'))
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='reviewstatus', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`status` IN ('pending', 'approved', 'rejected')", name=op.f('ck_reviews_status')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reviews_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('product_id', 'user_id', name=op.f('uq_reviews_product_id_user_id'))
    )
    op.create_index('ix_reviews_product_id_status', 'reviews', ['product_id', 'status'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_items_quantity_positive')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_cart_items_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items')),
    sa.UniqueConstraint('cart_id', 'variant_id', name=op.f('uq_cart_items_cart_id_variant_id'))
    )
    op.create_index(op.f('ix_cart_items_variant_id'), 'cart_items', ['variant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('variant_label', sa.String(length=200), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0 AND line_total >= 0', name=op.f('ck_order_items_amounts_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_order_items_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('alt', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_product_images_variant_id_product_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_images_variant_id'), 'product_images', ['variant_id'], unique=False)
    op.create_table('variant_attribute_values',
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('attribute_value_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], name=op.f('fk_variant_attribute_values_attribute_value_id_attribute_values')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_variant_attribute_values_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'attribute_value_id', name=op.f('pk_variant_attribute_values'))
    )
    op.create_index(op.f('ix_variant_attribute_values_attribute_value_id'), 'variant_attribute_values', ['attribute_value_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Indexes go away with their tables. Dropping them first fails in MySQL when a
    # foreign key needs them (error 1553), so only the tables are dropped.
    op.drop_table('variant_attribute_values')
    op.drop_table('product_images')
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('reviews')
    op.drop_table('product_variants')
    op.drop_table('product_translations')
    op.drop_table('payments')
    op.drop_table('order_status_history')
    op.drop_table('favorites')
    op.drop_table('coupon_redemptions')
    op.drop_table('addresses')
    op.drop_table('provinces')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('exchange_rates')
    op.drop_table('carts')
    op.drop_table('billing_profiles')
    op.drop_table('audit_logs')
    op.drop_table('attribute_values')
    op.drop_table('users')
    op.drop_table('shipping_zones')
    op.drop_table('pickup_points')
    op.drop_table('coupons')
    op.drop_table('categories')
    op.drop_table('brands')
    op.drop_table('attributes')
    # ### end Alembic commands ###
